default:
  PROJECT_NAME: "study"
  SECRET_KEY: "django-insecure-qd#x8e)f^km-8(%c2=y43s@@!y(rop&_tv&*&)t=8r6q@9l_*3"


development:
  DATABASE_URL: "postgresql://postgres:12345678@localhost:5432/space-db"

