default:
  ALLOWED_HOSTS: ""
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
    - scripts
    - static
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/project/templates/
  HOST: ""
  DOMAIN_NAME: "http://localhost:8000/"
  MODE_DEBUG: true
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: ""
  SECRET_KEY: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0
  EMAIL_HOST_PASSWORD: ''


development:
  HOST: "*"
  PORT: 8000
  WEB_CONCURRENCY: 2
  SECRET_KEY: "1"
  DATABASE_URL: "sqlite:///src/db.sqlite3"


ci:
  HOST: "localhost"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2
  DATABASE_URL: "sqlite:///src/db.sqlite3"
  MODE_DEBUG: false


docker:
  MODE_DEBUG: false
  DATABASE_URL: "postgresql://postgres:12345678@space-db:5432/space-db"

